#!/usr/bin/env python3
"""Flux preview workspace: canonical package map and combined verification."""
import argparse
import datetime
import json
import os
from pathlib import Path
import re
import signal
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parents[1]


def load():
    manifest = json.loads((ROOT / 'workspace.json').read_text())
    if manifest['format'] != 1:
        raise ValueError('unsupported workspace manifest')
    return manifest


def pack_config(manifest):
    lines = ['# Generated by python3 tools/workspace.py sync; edit workspace.json.',
             'collection = ' + json.dumps(manifest['collection']), '']
    for name, file in sorted(manifest['packages'].items()):
        path = Path(file)
        if path.is_absolute() or not (ROOT / path).resolve().is_relative_to(ROOT.resolve()):
            raise ValueError(f'package outside workspace: {name}')
        lines += [f'[custom.all.{name}]', 'type = "local"',
                  'path = ' + json.dumps(str(path.parent)), 'ipkg = ' + json.dumps(path.name)]
        if name in manifest.get('tests', {}):
            lines += ['test = ' + json.dumps(manifest['tests'][name])]
        lines += ['']
    # Pinned external dependencies: not vendored, so no workspace-relative
    # path check applies. Fetched by pack itself at the pinned commit.
    for name, dep in sorted(manifest.get('external_packages', {}).items()):
        lines += [f'[custom.all.{name}]', 'type = "git"',
                  'url = ' + json.dumps(dep['url']), 'commit = ' + json.dumps(dep['commit']),
                  'ipkg = ' + json.dumps(dep['ipkg'])]
        if 'test' in dep:
            lines += ['test = ' + json.dumps(dep['test'])]
        lines += ['']
    return '\n'.join(lines).rstrip() + '\n'


def dependencies(text):
    text = re.sub(r'--[^\n]*', '', text)
    # Bounds may span lines. Stop at the next package property, not at the
    # first newline; the graph is keyed by package name, never by its bounds.
    blocks = list(re.finditer(r'^\s*depends\s*=(.*?)(?=^\s*[A-Za-z][A-Za-z0-9_-]*\s*=(?!=)|\Z)',
                              text, re.M | re.S))
    if len(blocks) > 1:
        raise ValueError('multiple depends declarations are not supported by the workspace guard')
    names = set()
    if blocks:
        for clause in blocks[0][1].split(','):
            clause = clause.strip()
            if not clause:
                continue
            name = re.match(r'([A-Za-z0-9_][A-Za-z0-9_-]*)(?=\s|[<>=]|$)', clause)
            if not name:
                raise ValueError(f'cannot parse dependency name: {clause!r}')
            names.add(name[1])
    return names


def check(manifest):
    if (ROOT / 'pack.toml').read_text() != pack_config(manifest):
        raise ValueError('pack.toml is stale; run workspace.py sync')
    graph = {}
    for name, file in manifest['packages'].items():
        text = (ROOT / file).read_text()
        declared = re.search(r'^package\s+(\S+)', text, re.M)
        if not declared or declared[1] != name:
            raise ValueError(f'package identity mismatch: {file}')
        graph[name] = dependencies(text)
    for start in manifest['browser_roots']:
        seen, todo = set(), [start]
        while todo:
            name = todo.pop()
            if name in seen:
                continue
            seen.add(name)
            todo.extend(graph.get(name, set()))
        invalid = seen.intersection(manifest['browser_forbidden'])
        if invalid:
            raise ValueError(f'browser dependency boundary violated: {start} -> {sorted(invalid)}')
    for parent in ['packages', 'platform', 'examples', 'website']:
        for path in (ROOT / parent).rglob('pack.toml'):
            if not any(p in {'build', 'node_modules', '.git'} for p in path.relative_to(ROOT).parts):
                raise ValueError(f'nested package map shadows workspace: {path.relative_to(ROOT)}')
    print(f'PASS {len(graph)} local packages, canonical paths and browser dependency boundaries', flush=True)


def stop_group(process):
    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        pass
    # The immediate process may have exited while descendants survived.
    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    process.wait()


def run_step(name, args, cwd, reports, outcomes, timeout=600):
    print(f'RUN {name}: {" ".join(args)}', flush=True)
    started = time.monotonic()
    with (reports / f'{name}.log').open('w') as output:
        process = subprocess.Popen(args, cwd=cwd, stdout=output, stderr=subprocess.STDOUT,
                                   start_new_session=True)
        try:
            code = process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            stop_group(process)
            code = 124
        except BaseException:
            stop_group(process)
            raise
    outcomes.append({'name': name, 'command': args, 'exit': code,
                     'seconds': round(time.monotonic() - started, 2)})
    (reports / 'results.json').write_text(json.dumps(outcomes, indent=2) + '\n')
    if code:
        raise RuntimeError(f'{name} failed ({code}); see {reports / (name + ".log")}')


def test(manifest, without_db):
    check(manifest)
    # pack can clean the root build/ directory while installing local packages.
    reports = ROOT / '.workspace/reports' / datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
    reports.mkdir(parents=True)
    outcomes = []
    def run(name, args, cwd=ROOT):
        run_step(name, args, cwd, reports, outcomes)
    def build(file, js=False):
        run('build-' + file.replace('/', '-').replace('.ipkg', ''),
            ['pack', '--no-prompt'] + (['--cg', 'javascript'] if js else []) + ['build', file])
    try:
        run('workspace-unit', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tools', '-p', 'test_workspace.py'])
        run('cli-unit', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tools', '-p', 'test_flux.py'])
        run('dev-watch', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tools', '-p', 'test_devwatch.py'])
        run('dev-hot', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tools', '-p', 'test_hot.py'])
        run('ui-naming', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tools', '-p', 'test_ui_names.py'])
        run('db-naming', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tools', '-p', 'test_db_names.py'])
        run('package-naming', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tools', '-p', 'test_package_names.py'])
        run('generator', [sys.executable, '-m', 'unittest', 'discover', '-s', 'platform', '-p', 'test_generator.py'])
        for example in ['example', 'crud']:
            run('generated-' + example, [sys.executable, 'platform/generate.py', f'platform/{example}/schema.json', '--out', f'platform/{example}', '--check'])
        build('examples/use-cases.ipkg')
        run('example-use-cases', [sys.executable, 'examples/test_use_cases.py'])
        build('website/landing.ipkg')
        run('landing-browser', [sys.executable, 'website/test_site.py'])
        build('test/test.ipkg')
        run('flux-regression', ['./test/build/exec/flux-test'])
        # Install native dependencies first; Flux UI's packaged demo is not JS.
        # Native-only edits otherwise leave pack's installed bridge stale.
        (ROOT / 'platform/flux-client.ipkg').touch()
        run('install-client-native', ['pack', '--no-prompt', 'install', 'flux-client'])
        run('client-native-security', [sys.executable, 'platform/client/test/native.py'])
        build('platform/example/client-native-test.ipkg')
        build('platform/crud/native-auth-test.ipkg')
        # pack's dependency freshness checks do not track native C changes.
        # Refresh the manifest timestamp (not contents) to force prebuild/install
        # even in a warm pack cache; plain `pack install` can otherwise be a no-op.
        # postgres is an external git dependency (see workspace.json); its own
        # native/TLS verification is that repo's responsibility, not this gate's.
        (ROOT / 'packages/auth/flux-auth.ipkg').touch()
        run('install-auth-native', ['pack', '--no-prompt', 'install', 'flux-auth'])
        run('auth-native', ['bash', 'packages/auth/test/native.sh'])
        build('packages/auth/test/test.ipkg')
        build('packages/db/test/test.ipkg')
        for file in ['platform/example/example.ipkg', 'platform/example/pg-example.ipkg',
                     'platform/example/migrations.ipkg', 'platform/crud/server.ipkg']:
            build(file)
        for file in ['platform/example/client-web-test.ipkg', 'platform/crud/client-test.ipkg', 'platform/crud/ui.ipkg']:
            build(file, js=True)
        build('platform/auth-boundary/server.ipkg')
        run('auth-boundary', [sys.executable, 'platform/test_auth_boundary.py'])
        run('flux-ui-wire', [sys.executable, 'platform/test_wire.py'])
        if without_db:
            outcomes.append({'name': 'database-integration', 'skipped': True})
        else:
            run('durable-auth', [sys.executable, 'packages/auth/test/integration.py'])
            run('flux-ui-pg-migrations', [sys.executable, 'platform/test_pg_wire.py'])
            run('flux-ui-crud', [sys.executable, 'platform/test_crud.py'])
            run('flux-ui-app-cli', [sys.executable, 'platform/test_app.py'])
    finally:
        (reports / 'results.json').write_text(json.dumps(outcomes, indent=2) + '\n')
        print('Reports:', reports, flush=True)
    print('PASS selected workspace checks' if without_db else 'PASS combined workspace integration', flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=['sync', 'check', 'test'])
    parser.add_argument('--without-db', action='store_true', help='explicitly skip database integration')
    args = parser.parse_args()
    try:
        manifest = load()
        if args.command == 'sync':
            (ROOT / 'pack.toml').write_text(pack_config(manifest))
        elif args.command == 'check':
            check(manifest)
        else:
            test(manifest, args.without_db)
    except (OSError, ValueError, RuntimeError) as error:
        parser.exit(1, str(error) + '\n')


if __name__ == '__main__':
    main()
